name: Burning Cities
favicon: null
layout_spectrum: 0.3368943443056196
typography_spectrum: 0.9909656206145883
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#97b0e8'
    - '#6187d2'
    - '#072327'
    - '#424041'
    - '#bc9099'
  brandStrength: 1
  lightness: 0.1875
  saturation: 0.1875
  rhythmicContrast: 0.8810996990650892
purpose: []
